-- Brevado — v2 Epic D Part 1: add an auto-generated `title` to recordings.
--
-- A new migration rather than an edit to 0001_initial_schema.sql, per
-- docs/CLAUDE.md's convention ("add new schema changes as a new numbered
-- migration file rather than editing an applied one") — 0001 is already
-- applied to the live Supabase project.
--
-- `title` is a short 2-4 word label ("Challenging Coworker", "Day Recap")
-- generated by the existing Gemini feedback call (see
-- backend/app/services/feedback.py) and written when the pipeline reaches
-- `done`. Nullable, with no default: recordings created before this change
-- keep title = null (no backfill), and title generation failing for a new
-- recording also leaves it null without failing the recording (same lenient
-- degradation as metrics — see docs/CLAUDE.md's "Metrics" section). Part 2
-- makes it user-editable; Part 3+ displays it in History.

alter table public.recordings add column title text;
