-- Brevado — v3 Epic F Step 1: three per-recording scores + a grammar-issue count.
--
-- A new migration rather than an edit to an applied one, per docs/CLAUDE.md's
-- convention — 0001–0006 are already applied to the live Supabase project. Run
-- this SQL manually in the Supabase dashboard's SQL editor, same as the others.
--
-- v3 (Phase 6) adds three 0–100 integer scores to each recording — Impact,
-- Clarity, Structure (that display order) — generated by the SAME Gemini
-- feedback call that already returns `feedback` + `title`
-- (backend/app/services/feedback.py), extended to also return these in its
-- structured-JSON response. `grammar_issue_count` is a fourth value from that
-- call: a Clarity grounding input the model assesses itself (there's no
-- deterministic grammar check), not itself a displayed score.
--
-- All four are nullable with no default and there is NO backfill: recordings
-- created before this change keep them NULL, and a recording whose generation
-- succeeds for `feedback` but returns an unusable score also leaves that score
-- NULL without failing the recording (same lenient degradation as `title` /
-- metrics — see docs/CLAUDE.md's "v3 scope" and "Feedback generation"). Streaks
-- aggregation (v3 Epic G) excludes any recording with a NULL score.

alter table public.recordings add column impact_score integer;
alter table public.recordings add column clarity_score integer;
alter table public.recordings add column structure_score integer;
alter table public.recordings add column grammar_issue_count integer;
